package com.splitemapp.service.domainmodel.domain;

// Generated Sep 15, 2014 8:09:15 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ExpenseCategory generated by hbm2java
 */
@Entity
@Table(name = "expense_category", catalog = "splitshares", uniqueConstraints = @UniqueConstraint(columnNames = "cod"))
public class ExpenseCategory implements java.io.Serializable {

	private static final long serialVersionUID = -6784777617407039226L;
	private short id;
	private String cod;
	private String title;
	private Set<UserExpenses> userExpenseses = new HashSet<UserExpenses>(0);

	public ExpenseCategory() {
	}

	public ExpenseCategory(short id, String cod, String title) {
		this.id = id;
		this.cod = cod;
		this.title = title;
	}

	public ExpenseCategory(short id, String cod, String title,
			Set<UserExpenses> userExpenseses) {
		this.id = id;
		this.cod = cod;
		this.title = title;
		this.userExpenseses = userExpenseses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	@Column(name = "cod", unique = true, nullable = false, length = 64)
	public String getCod() {
		return this.cod;
	}

	public void setCod(String cod) {
		this.cod = cod;
	}

	@Column(name = "title", nullable = false, length = 64)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expenseCategory")
	public Set<UserExpenses> getUserExpenseses() {
		return this.userExpenseses;
	}

	public void setUserExpenseses(Set<UserExpenses> userExpenseses) {
		this.userExpenseses = userExpenseses;
	}

}
