package com.splitemapp.service.domainmodel.domain;

// Generated Sep 15, 2014 8:09:15 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GroupStatus generated by hbm2java
 */
@Entity
@Table(name = "group_status", catalog = "splitshares", uniqueConstraints = @UniqueConstraint(columnNames = "cod"))
public class GroupStatus implements java.io.Serializable {

	private static final long serialVersionUID = 8700853389002247470L;
	private short id;
	private String cod;
	private String title;
	private Set<Group> groups = new HashSet<Group>(0);

	public GroupStatus() {
	}

	public GroupStatus(short id, String cod, String title) {
		this.id = id;
		this.cod = cod;
		this.title = title;
	}

	public GroupStatus(short id, String cod, String title, Set<Group> groups) {
		this.id = id;
		this.cod = cod;
		this.title = title;
		this.groups = groups;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	@Column(name = "cod", unique = true, nullable = false, length = 64)
	public String getCod() {
		return this.cod;
	}

	public void setCod(String cod) {
		this.cod = cod;
	}

	@Column(name = "title", nullable = false, length = 64)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "groupStatus")
	public Set<Group> getGroups() {
		return this.groups;
	}

	public void setGroups(Set<Group> groups) {
		this.groups = groups;
	}

}
