package com.splitemapp.service.domainmodel.domain;

// Generated Sep 15, 2014 8:09:15 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ProjectStatus generated by hbm2java
 */
@Entity
@Table(name = "project_status", catalog = "splitshares", uniqueConstraints = @UniqueConstraint(columnNames = "cod"))
public class ProjectStatus implements java.io.Serializable {

	private static final long serialVersionUID = -1826170015585538581L;
	private short id;
	private String cod;
	private String title;
	private Set<Project> projects = new HashSet<Project>(0);

	public ProjectStatus() {
	}

	public ProjectStatus(short id, String cod, String title) {
		this.id = id;
		this.cod = cod;
		this.title = title;
	}

	public ProjectStatus(short id, String cod, String title,
			Set<Project> projects) {
		this.id = id;
		this.cod = cod;
		this.title = title;
		this.projects = projects;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	@Column(name = "cod", unique = true, nullable = false, length = 64)
	public String getCod() {
		return this.cod;
	}

	public void setCod(String cod) {
		this.cod = cod;
	}

	@Column(name = "title", nullable = false, length = 64)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectStatus")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

}
