package com.splitemapp.service.domainmodel.domain;

// Generated Sep 15, 2014 8:09:15 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserToGroup generated by hbm2java
 */
@Entity
@Table(name = "user_to_group", catalog = "splitshares", uniqueConstraints = @UniqueConstraint(columnNames = {
		"user_id", "group_id" }))
public class UserToGroup implements java.io.Serializable {

	private static final long serialVersionUID = 9173640802573250421L;
	private Long id;
	private User user;
	private Group group;
	private UserToGroupStatus userToGroupStatus;
	private boolean isAdmin;

	public UserToGroup() {
	}

	public UserToGroup(User user, Group group,
			UserToGroupStatus userToGroupStatus, boolean isAdmin) {
		this.user = user;
		this.group = group;
		this.userToGroupStatus = userToGroupStatus;
		this.isAdmin = isAdmin;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id", nullable = false)
	public Group getGroup() {
		return this.group;
	}

	public void setGroup(Group group) {
		this.group = group;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_status_id", nullable = false)
	public UserToGroupStatus getUserToGroupStatus() {
		return this.userToGroupStatus;
	}

	public void setUserToGroupStatus(UserToGroupStatus userToGroupStatus) {
		this.userToGroupStatus = userToGroupStatus;
	}

	@Column(name = "is_admin", nullable = false)
	public boolean isIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(boolean isAdmin) {
		this.isAdmin = isAdmin;
	}

}
