package com.splitemapp.service.domainmodel.domain;

// Generated Sep 15, 2014 8:09:15 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UserContactData generated by hbm2java
 */
@Entity
@Table(name = "user_contact_data", catalog = "splitshares", uniqueConstraints = @UniqueConstraint(columnNames = {
		"user_id", "contact_data" }))
public class UserContactData implements java.io.Serializable {

	private static final long serialVersionUID = 8927823575372766924L;
	private Long id;
	private User user;
	private String contactData;
	private boolean verified;
	private Date verifiedAt;
	private Date createdAt;
	private Date updatedAt;

	public UserContactData() {
	}

	public UserContactData(User user, boolean verified, Date createdAt) {
		this.user = user;
		this.verified = verified;
		this.createdAt = createdAt;
	}

	public UserContactData(User user, String contactData, boolean verified,
			Date verifiedAt, Date createdAt, Date updatedAt) {
		this.user = user;
		this.contactData = contactData;
		this.verified = verified;
		this.verifiedAt = verifiedAt;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "contact_data", length = 64)
	public String getContactData() {
		return this.contactData;
	}

	public void setContactData(String contactData) {
		this.contactData = contactData;
	}

	@Column(name = "verified", nullable = false)
	public boolean isVerified() {
		return this.verified;
	}

	public void setVerified(boolean verified) {
		this.verified = verified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "verified_at", length = 19)
	public Date getVerifiedAt() {
		return this.verifiedAt;
	}

	public void setVerifiedAt(Date verifiedAt) {
		this.verifiedAt = verifiedAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", length = 19)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

}
