package com.splitemapp.commons.domain;

// Generated Sep 15, 2014 8:09:15 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.splitemapp.commons.constants.TableName;

/**
 * ProjectStatus generated by hbm2java
 */
@Entity(name = TableName.EXPENSE_STATUS)
@Table(name = TableName.EXPENSE_STATUS, catalog = TableName.SCHEMA, uniqueConstraints = @UniqueConstraint(columnNames = "cod"))
public class ExpenseStatus implements java.io.Serializable {

	private static final long serialVersionUID = -1826170015585538581L;
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	private Short id;
	
	@Column(name = "cod", unique = true, nullable = false, length = 64)
	private String cod;
	
	@Column(name = "title", nullable = false, length = 64)
	private String title;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expenseStatus")
	private Set<UserExpense> userExpenses = new HashSet<UserExpense>(0);

	public ExpenseStatus() {
	}

	public ExpenseStatus(Short id, String cod, String title) {
		this.id = id;
		this.cod = cod;
		this.title = title;
	}

	public ExpenseStatus(Short id, String cod, String title,
			Set<UserExpense> userExpenses) {
		this.id = id;
		this.cod = cod;
		this.title = title;
		this.userExpenses = userExpenses;
	}

	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	public String getCod() {
		return this.cod;
	}

	public void setCod(String cod) {
		this.cod = cod;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Set<UserExpense> getUserExpenses() {
		return this.userExpenses;
	}

	public void setProjects(Set<UserExpense> userExpenses) {
		this.userExpenses = userExpenses;
	}

}
