package com.splitemapp.commons.domain;

// Generated Sep 15, 2014 8:09:15 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.splitemapp.commons.constants.TableName;

/**
 * InviteStatus generated by hbm2java
 */
@Entity(name = TableName.INVITE_STATUS)
@Table(name = TableName.INVITE_STATUS, catalog = TableName.SCHEMA, uniqueConstraints = @UniqueConstraint(columnNames = "cod"))
public class InviteStatus implements java.io.Serializable {

	private static final long serialVersionUID = -1943633347091729409L;
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	private Short id;
	
	@Column(name = "cod", unique = true, nullable = false, length = 64)
	private String cod;
	
	@Column(name = "title", nullable = false, length = 64)
	private String title;
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inviteStatus")
	private Set<UserInvite> userInvites = new HashSet<UserInvite>(0);

	public InviteStatus() {
	}

	public InviteStatus(Short id, String cod, String title) {
		this.id = id;
		this.cod = cod;
		this.title = title;
	}

	public InviteStatus(Short id, String cod, String title,
			Set<UserInvite> userInvites) {
		this.id = id;
		this.cod = cod;
		this.title = title;
		this.userInvites = userInvites;
	}

	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	public String getCod() {
		return this.cod;
	}

	public void setCod(String cod) {
		this.cod = cod;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Set<UserInvite> getUserInvites() {
		return this.userInvites;
	}

	public void setUserInvites(Set<UserInvite> userInvites) {
		this.userInvites = userInvites;
	}
	
}
