package com.splitemapp.commons.domain;

// Generated Sep 15, 2014 8:09:15 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.j256.ormlite.field.DataType;
import com.j256.ormlite.field.DatabaseField;
import com.splitemapp.commons.domain.dto.ProjectCoverImageDTO;

/**
 * UserContactData generated by hbm2java
 */
@Entity(name = "project_cover_image")
@Table(name = "project_cover_image", catalog = "splitemapp", uniqueConstraints = @UniqueConstraint(columnNames = "project_id"))
public class ProjectCoverImage implements java.io.Serializable, PushableEntity {

	private static final long serialVersionUID = 8927823575372766924L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	@DatabaseField(allowGeneratedIdInsert = true, generatedId = true)
	private Long id;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id", nullable = false)
	private Project project;
	
	@Column(name = "avatar_data")
	@DatabaseField(dataType = DataType.BYTE_ARRAY)
	private byte[] avatarData;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	private Date createdAt;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	private Date updatedAt;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pushed_at", length = 19)
	private Date pushedAt;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "updated_by", nullable = false)
	private User updatedBy;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pushed_by")
	private User pushedBy;

	public ProjectCoverImage() {
		this.createdAt = this.updatedAt = new Date();
	}
	
	public ProjectCoverImage(Project project, User updatedBy, User pushedBy, ProjectCoverImageDTO projectCoverImageDTO){
		this.id = projectCoverImageDTO.getId();
		this.project = project;
		this.avatarData = projectCoverImageDTO.getAvatarData();
		this.createdAt = projectCoverImageDTO.getCreatedAt();
		this.updatedAt = projectCoverImageDTO.getUpdatedAt();
		this.updatedBy = updatedBy;
		this.pushedAt = projectCoverImageDTO.getPushedAt();
		this.pushedBy = pushedBy;
	}

	public ProjectCoverImage(Project project, byte[] avatarData, Date createdAt, Date updatedAt, Date pushedAt) {
		this.project = project;
		this.avatarData = avatarData;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.pushedAt = pushedAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public byte[] getAvatarData() {
		return avatarData;
	}

	public void setAvatarData(byte[] avatarData) {
		this.avatarData = avatarData;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Override
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	@Override
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Override
	public Date getPushedAt() {
		return pushedAt;
	}

	@Override
	public void setPushedAt(Date pushedAt) {
		this.pushedAt = pushedAt;
	}

	@Override
	public User getUpdatedBy() {
		return updatedBy;
	}

	@Override
	public void setUpdatedBy(User updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Override
	public User getPushedBy() {
		return pushedBy;
	}

	@Override
	public void setPushedBy(User pushedBy) {
		this.pushedBy = pushedBy;
	}

}
