package com.splitemapp.commons.domain;

// Generated Sep 15, 2014 8:09:15 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.splitemapp.commons.constants.TableName;
import com.splitemapp.commons.domain.dto.UserContactDataDTO;

/**
 * UserContactData generated by hbm2java
 */
@Entity(name = TableName.USER_CONTACT_DATA)
@Table(name = TableName.USER_CONTACT_DATA, catalog = "splitemapp", uniqueConstraints = @UniqueConstraint(columnNames = {
		"user_id", "contact_data" }))
public class UserContactData extends BaseUpdateableEntity implements java.io.Serializable {

	private static final long serialVersionUID = 8927823575372766924L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	private User user;

	@Column(name = "contact_data", length = 64)
	private String contactData;

	@Column(name = "verified", nullable = false)
	private boolean verified;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "verified_at", length = 19)
	private Date verifiedAt;

	public UserContactData() {
	}
	
	public UserContactData(User user, UserContactDataDTO userContactDataDTO) {
		this.id = userContactDataDTO.getId();
		this.user = user;
		this.contactData = userContactDataDTO.getContactData();
		this.verified = userContactDataDTO.isVerified();
		this.verifiedAt = userContactDataDTO.getVerifiedAt();
	}
	
	public UserContactData(Long id, User user, String contactData,
			boolean verified, Date verifiedAt) {
		this.id = id;
		this.user = user;
		this.contactData = contactData;
		this.verified = verified;
		this.verifiedAt = verifiedAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getContactData() {
		return this.contactData;
	}

	public void setContactData(String contactData) {
		this.contactData = contactData;
	}

	public boolean isVerified() {
		return this.verified;
	}

	public void setVerified(boolean verified) {
		this.verified = verified;
	}

	public Date getVerifiedAt() {
		return this.verifiedAt;
	}

	public void setVerifiedAt(Date verifiedAt) {
		this.verifiedAt = verifiedAt;
	}

}
