package com.splitemapp.commons.domain;

// Generated Sep 15, 2014 8:09:15 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.splitemapp.commons.constants.TableName;
import com.splitemapp.commons.domain.dto.UserExpenseDTO;

/**
 * UserExpense generated by hbm2java
 */
@Entity(name = TableName.USER_EXPENSE)
@Table(name = TableName.USER_EXPENSE, catalog = TableName.SCHEMA)
public class UserExpense extends BaseUpdateableEntity implements java.io.Serializable {

	private static final long serialVersionUID = 2204965154783892793L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	private User user;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id", nullable = false)
	private Project project;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "category_id", nullable = false)
	private ExpenseCategory expenseCategory;

	@Column(name = "expense", nullable = false, precision = 16, scale = 6)
	private BigDecimal expense;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expense_date", length = 19)
	private Date expenseDate;

	@Column(name = "note", length = 65535)
	private String note;

	public UserExpense() {
	}
	
	public UserExpense(User user, Project project,
			ExpenseCategory expenseCategory, UserExpenseDTO userExpenseDTO) {
		super(userExpenseDTO.getCreatedAt(), userExpenseDTO.getUpdatedAt());
		this.id = userExpenseDTO.getId();
		this.user = user;
		this.project = project;
		this.expenseCategory = expenseCategory;
		this.expense = userExpenseDTO.getExpense();
		this.expenseDate = userExpenseDTO.getExpenseDate();
		this.note = userExpenseDTO.getNote();
	}

	public UserExpense(Long id, User user, Project project,
			ExpenseCategory expenseCategory, BigDecimal expense,
			Date expenseDate, String note) {
		this.id = id;
		this.user = user;
		this.project = project;
		this.expenseCategory = expenseCategory;
		this.expense = expense;
		this.expenseDate = expenseDate;
		this.note = note;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public ExpenseCategory getExpenseCategory() {
		return this.expenseCategory;
	}

	public void setExpenseCategory(ExpenseCategory expenseCategory) {
		this.expenseCategory = expenseCategory;
	}

	public BigDecimal getExpense() {
		return this.expense;
	}

	public void setExpense(BigDecimal expense) {
		this.expense = expense;
	}

	public Date getExpenseDate() {
		return this.expenseDate;
	}

	public void setExpenseDate(Date expenseDate) {
		this.expenseDate = expenseDate;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
