package com.splitemapp.commons.domain;

// Generated Sep 15, 2014 8:09:15 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserSession generated by hbm2java
 */
@Entity(name = "user_session")
@Table(name = "user_session", catalog = "splitemapp")
public class UserSession implements java.io.Serializable {

	private static final long serialVersionUID = 935924848642967248L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	private User user;

	@Column(name = "token", unique = true, length = 64, nullable = false)
	private String token;
	
	@Column(name = "device", length = 64, nullable = false)
	private String device;
	
	@Column(name = "os_version", length = 64, nullable = false)
	private String osVersion;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_used_at", length = 19, nullable = false)
	private Date lastUsedAt;

	public UserSession() {
	}

	public UserSession(User user, String token, String device, String osVersion, Date lastUsedAt) {
		this.user = user;
		this.token = token;
		this.device = device;
		this.osVersion = osVersion;
		this.lastUsedAt = lastUsedAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}
	
	public String getDevice() {
		return this.device;
	}

	public void setDevice(String device) {
		this.device = device;
	}

	public String getOsVersion() {
		return osVersion;
	}

	public void setOsVersion(String osVersion) {
		this.osVersion = osVersion;
	}

	public Date getLastUsedAt() {
		return this.lastUsedAt;
	}

	public void setLastUsedAt(Date lastUsedAt) {
		this.lastUsedAt = lastUsedAt;
	}

}
