package com.splitemapp.commons.domain;

// Generated Sep 15, 2014 8:09:15 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.j256.ormlite.field.DatabaseField;
import com.splitemapp.commons.domain.dto.UserInviteDTO;
import com.splitemapp.commons.utils.TimeUtils;

/**
 * UserInvite generated by hbm2java
 */
@Entity(name = "user_invite")
@Table(name = "user_invite", catalog = "splitemapp")
public class UserInvite implements java.io.Serializable,PushableEntity {

	private static final long serialVersionUID = -2499430771175807337L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	@DatabaseField(allowGeneratedIdInsert = true, generatedId = true)
	private Long id;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	private User user;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id", nullable = false)
	private Project project;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "status_id", nullable = false)
	private InviteStatus inviteStatus;

	@Column(name = "email", length = 64)
	private String email;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	private Date createdAt;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	private Date updatedAt;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pushed_at", length = 19)
	private Date pushedAt;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "updated_by", nullable = false)
	private User updatedBy;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pushed_by")
	private User pushedBy;

	public UserInvite() {
		this.createdAt = this.updatedAt = TimeUtils.getUTCDate();
	}
	
	public UserInvite(User user, Project project, InviteStatus inviteStatus, User updatedBy, User pushedBy, UserInviteDTO userInviteDTO) {
		this.id = userInviteDTO.getId();
		this.user = user;
		this.project = project;
		this.inviteStatus = inviteStatus;
		this.email = userInviteDTO.getEmail();
		this.createdAt = userInviteDTO.getCreatedAt();
		this.updatedAt = userInviteDTO.getUpdatedAt();
		this.updatedBy = updatedBy;
		this.pushedAt = userInviteDTO.getPushedAt();
		this.pushedBy = pushedBy;
	}

	public UserInvite(User user, Project project, InviteStatus inviteStatus,
			Date createdAt, Date updatedAt, Date pushedAt) {
		this.user = user;
		this.project = project;
		this.inviteStatus = inviteStatus;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.pushedAt = pushedAt;
	}

	public UserInvite(User user, Project project, InviteStatus inviteStatus,
			String email, Date createdAt, Date updatedAt, Date pushedAt) {
		this.user = user;
		this.project = project;
		this.inviteStatus = inviteStatus;
		this.email = email;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.pushedAt = pushedAt;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public InviteStatus getInviteStatus() {
		return this.inviteStatus;
	}

	public void setInviteStatus(InviteStatus inviteStatus) {
		this.inviteStatus = inviteStatus;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Override
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	@Override
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Override
	public Date getPushedAt() {
		return pushedAt;
	}

	@Override
	public void setPushedAt(Date pushedAt) {
		this.pushedAt = pushedAt;
	}

	@Override
	public User getUpdatedBy() {
		return updatedBy;
	}

	@Override
	public void setUpdatedBy(User updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Override
	public User getPushedBy() {
		return pushedBy;
	}

	@Override
	public void setPushedBy(User pushedBy) {
		this.pushedBy = pushedBy;
	}

}
