package com.splitemapp.commons.domain;

// Generated Sep 15, 2014 8:09:15 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.splitemapp.commons.constants.TableName;

/**
 * UserInvite generated by hbm2java
 */
@Entity(name = TableName.USER_INVITE)
@Table(name = TableName.USER_INVITE, catalog = "splitemapp")
public class UserInvite extends BaseUpdateableEntity implements java.io.Serializable {

	private static final long serialVersionUID = -2499430771175807337L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	private User user;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id", nullable = false)
	private Project project;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "status_id", nullable = false)
	private InviteStatus inviteStatus;

	@Column(name = "email", length = 64)
	private String email;

	public UserInvite() {
	}
	
	public UserInvite(Long id, User user, Project project,
			InviteStatus inviteStatus, String email) {
		this.id = id;
		this.user = user;
		this.project = project;
		this.inviteStatus = inviteStatus;
		this.email = email;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public InviteStatus getInviteStatus() {
		return this.inviteStatus;
	}

	public void setInviteStatus(InviteStatus inviteStatus) {
		this.inviteStatus = inviteStatus;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
