package com.splitemapp.commons.domain;

// Generated Sep 15, 2014 8:09:15 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * UserToProjectStatus generated by hbm2java
 */
@Entity(name = "user_to_project_status")
@Table(name = "user_to_project_status", catalog = "splitemapp", uniqueConstraints = @UniqueConstraint(columnNames = "cod"))
public class UserToProjectStatus implements java.io.Serializable {

	private static final long serialVersionUID = -8633833853020106879L;

	@Id
	@Column(name = "id", unique = true, nullable = false)
	private Short id;

	@Column(name = "cod", unique = true, nullable = false, length = 64)
	private String cod;

	@Column(name = "title", nullable = false, length = 64)
	private String title;

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "userToProjectStatus")
	private Set<UserToProject> userToProjects = new HashSet<UserToProject>(0);

	public UserToProjectStatus() {
	}

	public UserToProjectStatus(Short id, String cod, String title) {
		this.id = id;
		this.cod = cod;
		this.title = title;
	}

	public UserToProjectStatus(Short id, String cod, String title,
			Set<UserToProject> userToProjects) {
		this.id = id;
		this.cod = cod;
		this.title = title;
		this.userToProjects = userToProjects;
	}

	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	public String getCod() {
		return this.cod;
	}

	public void setCod(String cod) {
		this.cod = cod;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Set<UserToProject> getUserToProjects() {
		return this.userToProjects;
	}

	public void setUserToProjects(Set<UserToProject> userToProjects) {
		this.userToProjects = userToProjects;
	}
	
}
