package com.splitemapp.commons.domain;

// Generated Sep 15, 2014 8:09:15 PM by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.j256.ormlite.field.DatabaseField;
import com.splitemapp.commons.domain.dto.UserExpenseDTO;

/**
 * UserExpense generated by hbm2java
 */
@Entity(name = "user_expense")
@Table(name = "user_expense", catalog = "splitemapp")
public class UserExpense implements java.io.Serializable,PushableEntity {

	private static final long serialVersionUID = 2204965154783892793L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	@DatabaseField(allowGeneratedIdInsert = true, generatedId = true)
	private Long id;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", nullable = false)
	private User user;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "project_id", nullable = false)
	private Project project;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "category_id", nullable = false)
	private ExpenseCategory expenseCategory;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "status_id", nullable = false)
	private ExpenseStatus expenseStatus;

	@Column(name = "expense", nullable = false, precision = 16, scale = 6)
	private BigDecimal expense;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_at", nullable = false, length = 19)
	private Date createdAt;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_at", nullable = false, length = 19)
	private Date updatedAt;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pushed_at", length = 19)
	private Date pushedAt;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "updated_by", nullable = false)
	private User updatedBy;
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pushed_by")
	private User pushedBy;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expense_date", length = 19)
	private Date expenseDate;

	@Column(name = "note", length = 65535)
	private String note;

	public UserExpense() {
		this.createdAt = this.updatedAt = new Date();
	}
	
	public UserExpense(User user, Project project,
			ExpenseCategory expenseCategory, ExpenseStatus expenseStatus, User updatedBy, User pushedBy, UserExpenseDTO userExpenseDTO) {
		this.id = userExpenseDTO.getId();
		this.user = user;
		this.project = project;
		this.expenseCategory = expenseCategory;
		this.expenseStatus = expenseStatus;
		this.expense = userExpenseDTO.getExpense();
		this.expenseDate = userExpenseDTO.getExpenseDate();
		this.note = userExpenseDTO.getNote();
		this.createdAt = userExpenseDTO.getCreatedAt();
		this.updatedAt = userExpenseDTO.getUpdatedAt();
		this.updatedBy = updatedBy;
		this.pushedAt = userExpenseDTO.getPushedAt();
		this.pushedBy = pushedBy;
	}

	public UserExpense(User user, Project project,
			ExpenseCategory expenseCategory, ExpenseStatus expenseStatus, BigDecimal expense) {
		this.user = user;
		this.project = project;
		this.expenseCategory = expenseCategory;
		this.expenseStatus = expenseStatus;
		this.expense = expense;
	}

	public UserExpense(User user, Project project,
			ExpenseCategory expenseCategory, ExpenseStatus expenseStatus, BigDecimal expense,
			Date expenseDate, String note) {
		this.user = user;
		this.project = project;
		this.expenseCategory = expenseCategory;
		this.expenseStatus = expenseStatus;
		this.expense = expense;
		this.expenseDate = expenseDate;
		this.note = note;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public ExpenseCategory getExpenseCategory() {
		return this.expenseCategory;
	}

	public void setExpenseCategory(ExpenseCategory expenseCategory) {
		this.expenseCategory = expenseCategory;
	}
	
	public ExpenseStatus getExpenseStatus() {
		return this.expenseStatus;
	}

	public void setExpenseStatus(ExpenseStatus expenseStatus) {
		this.expenseStatus = expenseStatus;
	}

	public BigDecimal getExpense() {
		return this.expense;
	}

	public void setExpense(BigDecimal expense) {
		this.expense = expense;
	}

	public Date getExpenseDate() {
		return this.expenseDate;
	}

	public void setExpenseDate(Date expenseDate) {
		this.expenseDate = expenseDate;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public Date getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Override
	public Date getUpdatedAt() {
		return updatedAt;
	}

	@Override
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Override
	public Date getPushedAt() {
		return pushedAt;
	}

	@Override
	public void setPushedAt(Date pushedAt) {
		this.pushedAt = pushedAt;
	}

	@Override
	public User getUpdatedBy() {
		return updatedBy;
	}

	@Override
	public void setUpdatedBy(User updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Override
	public User getPushedBy() {
		return pushedBy;
	}

	@Override
	public void setPushedBy(User pushedBy) {
		this.pushedBy = pushedBy;
	}

}
